### PR TITLE
Adds Dropbox support.

### PR DESCRIPTION
**Pull request by tempelmann**
Requires generating and setting of Dropbox "App Key" (see instructions at top of wwwsqldesigner.js)

This also fixes a different little issue: The "_name" property is supposed to remember the last used name (key) for saving and loading, but it wasn't getting remembered for local (browser storage) operations. It is now, so that after loading, a save operation will offer the previous name again.

I'd also like to hide the Dropbox buttons if they can't be used (if either the browser doesn't support the Dropbox API or if the App Key is not set) but I don't know how to do that best. Please advise.

### CODE REVIEW

**Comment by ondras** [comment]
Hi,

thanks a lot for this feature! I am going to merge it sooner or later. A few comments:

  1. generally, the save/load engine shall be rewritten to allow for pluggable storage backends - Dropbox, GDrive, Firebase, current REST API servers. This should include some selectbox-based UI to avoid cluttering the space with zillion buttons.
  1. thanks for the spelling fixes and code cleanups, including `fromXMLText1`
  1. hiding dropbox buttons: 
```js
var buttons = document.querySelectorAll("[id^=clientdropbox]");
[].slice.call(buttons).forEach(function(button) { button.style.display = "none"; }));
```
(alternatively, one can remove those buttons from the DOM instead)

**Comment by tempelmann** [comment]
Okay, let me add a fix more fixes. I'll add the buttons hiding and also add a trim call to the SQL output, because at least with sqlite, I keep getting a few empty lines at the start without it.

Also, I currently have added two dropbox helper functions to the global level (window), and not to a namespace like you did with all your functions. Shall I change that? To which namespace should I add them, then? (I have almost no practice with JS, so I don't even understand why you're using prototypes like that, especially since you're not building a lib here but an app.)

**Comment by ondras** [comment]
Generally speaking, there is nothing specific about "libs" or "apps" with respect to prototypes. Prototypes are used in places where code/logic sharing is feasible, such as instantiable functions (`SQL.Table`) or extensible objects (`SQL.Visual`). You define your logic once - on a function's prototype - and then have all instances/descendants share that code via a prototype link.

The current solution, "have everything in SQL.IO", is no longer maintainable. I will probably refactor the relevant code and introduce the notion of an abstract `SQL.Backend` object, that would be sublassed by a specialied "dropbox", "local", "rest" etc. variants.

This being said, feel free to leave your logic in the global namespace. I will take care about it during the refactoring (that would also imply splitting the code into smaller pieces; the current monolithic solution has truly overgrown its initial - very old - ambitions).

**Comment by tempelmann** [comment]
I have refactored the code to use the IO namespace for now as I wanted to figure out how that works, and to make it fit better into the rest of the code. I have also added hiding of the dropbox buttons and changed the html and CSS a little to make the load/save dialog wider in order to fit the 3 buttons in a single row. I also now store the last used name (key) in a cookie so that it is re-used next time you load the page and then try to load from localstorage or dropbox. I did not mess with the "_name" property that's used for the saver file name as I was not sure if they should be mixed (especially due to the quicksave button which may cause unwanted effects otherwise).

**Comment by ondras** [comment]
Cool, thanks a lot! I will do the necessary adjustments for more cloud storage options soon, when I have some time.

**Comment by ondras** [comment]
The dropbox app key is now moved to `config.js`.

**Comment by ondras** [comment]
@tempelmann would you please have a look at the https://github.com/ondras/wwwsqldesigner/tree/storage branch? I refactored all the storage code significantly, including your Dropbox client. I would like to make sure everything works - and I do not have Dropbox myself.

Also, your auth routine (`showDropboxAuthenticate`) seems to always return `false` in the asynchronous case, when you call `this.dropboxClient.authenticate`. Is this correct? I would say that perhaps the whole `showDropboxAuthenticate` shall be asynchronous...

**Comment by tempelmann** [comment]
You may be right on the showDropboxAuthenticate part. I'll check later today.

**Comment by tempelmann** [comment]
The dropbox code is still functional in the storage branch. But loading / saving with the new popup (for browserstorage) doesn't work any more: There is currently no way to enter a new name. And initially, when the popup has no selection (at least on Safari/OSX), loading leads to a nonsense error msg. It should then at least say: "please select a file from the left popup menu first." - or even pre-select the last used name (using cookies).

I'll look into the dropbox auth issue now.

**Comment by tempelmann** [comment]
Alright, I fixed authentication in both branches. Sorry for using a helper var again to refer to "this" inside the callback functions. I still have trouble understanding JS's weird scope rules.

**Comment by ondras** [comment]
I added some scope-related comments to the relevant PR.

Are your comments re. broken saving/loading still relevant? As far as the Browser storage goes, just unselect (ctrl-click) a row to save under a new name. Perhaps a "[pick new name]" default row would solve this?

**Comment by tempelmann** [comment]
Thanks for explaining the scope rules and bind() function. Had been wondering what that was for.

I'll add more info to the bug report on Load/Save

**Pull request merged**
